package net.Indyuce.bountyhunters.version;

import net.Indyuce.bountyhunters.BountyHunters;
import org.bukkit.Sound;

// Legacy name | second parameter
// 1.12-1.16   | sound in enum name
// 1.16+       | first parameter
public enum VersionSound {
    ENTITY_ENDERMAN_HURT("ENTITY_ENDERMAN_HURT", "ENTITY_ENDERMEN_HURT"),
    ENTITY_ENDERMAN_DEATH("ENTITY_ENDERMAN_DEATH", "ENTITY_ENDERMEN_DEATH"),
    ENTITY_ENDERMAN_TELEPORT("ENTITY_ENDERMAN_TELEPORT", "ENTITY_ENDERMEN_TELEPORT"),
    ENTITY_FIREWORK_ROCKET_LARGE_BLAST("ENTITY_FIREWORK_ROCKET_LARGE_BLAST", "ENTITY_FIREWORK_LARGE_BLAST"),
    ENTITY_FIREWORK_ROCKET_TWINKLE("ENTITY_FIREWORK_ROCKET_TWINKLE", "ENTITY_FIREWORK_TWINKLE"),
    ENTITY_FIREWORK_ROCKET_BLAST("ENTITY_FIREWORK_ROCKET_BLAST", "ENTITY_FIREWORK_BLAST"),
    ENTITY_ZOMBIE_PIGMAN_ANGRY("ENTITY_ZOMBIFIED_PIGLIN_ANGRY", "ENTITY_ZOMBIE_PIG_ANGRY"),
    ENTITY_SHEEP_DEATH("ENTITY_SHEEP_DEATH", "ENTITY_SHEEP_DEATH"),
    ENTITY_GENERIC_EXPLODE("ENTITY_GENERIC_EXPLODE", "ENTITY_GENERIC_EXPLODE"),
    BLOCK_NOTE_BLOCK_HAT("BLOCK_NOTE_BLOCK_HAT", "BLOCK_NOTE_HAT"),
    BLOCK_NOTE_BLOCK_PLING("BLOCK_NOTE_BLOCK_PLING", "BLOCK_NOTE_PLING"),
    ENTITY_ZOMBIE_ATTACK_WOODEN_DOOR("ENTITY_ZOMBIE_ATTACK_WOODEN_DOOR", "ENTITY_ZOMBIE_ATTACK_DOOR_WOOD"),
    ENTITY_ENDER_DRAGON_GROWL("ENTITY_ENDER_DRAGON_GROWL", "ENTITY_ENDERDRAGON_GROWL"),
    ENTITY_ENDER_DRAGON_FLAP("ENTITY_ENDER_DRAGON_FLAP", "ENTITY_ENDERDRAGON_FLAP"),

    ;

    private final Sound sound;

    VersionSound(String v1_16, String legacy) {
        final PluginVersion ver = BountyHunters.getInstance().getVersion();
        sound = Sound.valueOf(ver.isStrictlyHigher(1, 15) ? v1_16
                : ver.isStrictlyHigher(1, 12) ? name() : legacy);
    }

    public Sound toSound() {
        return sound;
    }
}
